#!/usr/bin/python3
import subprocess
result = subprocess.run(['dokku', 'apps:list'], stdout=subprocess.PIPE, text=True).stdout
apps = [app for app in result.split('\n') if app][1:] # Ignore the first line since it's the "=====> My Apps"

print(apps)
